### ISSUE TITLE
TODO: Improve on current code

### ISSUE THREAD

**Issue by mathiasayivor** [MichaelMatros/ByAuthorProjectA#3]
The current code (especially CSS) needs a bit of refactoring. This improvement may help us in terms of code reuse, etc.
This issue is to serve as a to-do reminder.

**Comment by mathiasayivor** [comment]
Follow-up: As part of the process, [tailwindcss](https://tailwindcss.com) has been added.
Further steps left:
- [ ] Change all CSS code to tailwind
- [ ] 2.1 Break blocks down into components wherever necessary
- [ ] 2.2 Use tailwind classes in components where possible (except for edge cases where custom css is required)
